name: Unit Testing, Flake8, MyPy, iSort, and Black

on: 
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCE_SERVICE_ACCOUNT_KEY }}
          project_id: sense-staging
          export_default_credentials: true

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements_dev.txt
          pip install -r requirements.txt

      - run: isort --diff .
      - run: black --check .
      - run: flake8
      - run: mypy
      - run: pytest --cov --cov-fail-under=90 --cov-report term-missing
